---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

*20200924* 

# Train with DLC

Pilot videos here: `/nfs/ftp/private/birney-res-ftp/upload/medaka/videos/ian_pilot/all`

## Install DeepLabCut on local

Following tutorial here: <https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md>

```{bash}
# move to repo directory
cd ~/Documents/Repositories
# clone repo
git clone https://github.com/AlexEMG/DeepLabCut.git
# move into repo
cd DeepLabCut
# create environment - note creating CPU version
conda env create -f conda-environments/DLC-CPU.yaml
# activate env
conda activate DLC-CPU
# upgrade to version 2.2b8
pip install deeplabcut==2.2b8 # NOTE: this didn't work, but rather I re-created the env having edited the YAML to specify this version
# activate python to start GUI
pythonw
```

Start GUI

```{python}
# import
import deeplabcut
# check version
deeplabcut.__version__
# launch GUI
deeplabcut.launch_dlc()
```

## Import 10 videos for training

Saved here: `data/20201019_training_vids.txt`

* 20190611_1628_icab_hdr_R.avi
* 20190612_0952_icab_icab_R.avi
* 20190613_1024_icab_hni_R.avi
* 20190614_1208_icab_icab_L.avi
* 20190614_1456_icab_ho5_R.avi
* 20190614_1553_icab_hni_L.avi
* 20190615_1051_icab_hdr_L.avi
* 20190615_1518_icab_kaga_L.avi
* 20190616_1017_icab_kaga_R.avi
* 20190616_1622_icab_ho5_L.avi

```{bash}
for i in $( cat data/20201019_training_vids.txt ) ; do
  scp brettell@ebi:/nfs/ftp/private/birney-res-ftp/upload/medaka/videos/ian_pilot/all/$i \
  ~/Documents/Data/20201019_pilot_dlc_training ;
done  
```

## Project admin

* Project name: `~/Documents/pilot_paper`
* 10 videos loaded from `~/Documents/Data/20201019_pilot_dlc_training`
* config.yaml: `~/Documents/pilot_paper-ian_brettell-2020-10-21/config.yaml`
### Extract frames
* Use `uniform` not `kmeans` to extract frames, because the latter takes empty frames and ones with my arm in it. 

### Skeleton

```{r}
# Create vector of all body parts
bparts = c("nose", "head", "left_eye", "right_eye","spine_1", "spine_2", "spine_3", "spine_4", "spine_5", "tail_fin")
# Create pair-wise combinations
bpart_combs = t(combn(bparts, 2))

write.table(bpart_combs, here("data", "20201022_body_part_combinations.txt"),
            row.names = F,
            col.names = F,
            quote = F,
            sep = "\t")
# Then manually adjusted file on text editor
```

# Create conda environments for project

```{bash}
cd ~/Documents/Repositories/pilot_paper
# Python env
## Create env
conda create -n pilot_env_py python=3.6 biopython
## Activate env
conda activate pilot_env_py
## List current packages
conda list
## Install packages
conda install -c anaconda opencv
conda install -c anaconda pandas
## Write to file
conda env export -n pilot_env_py -f config/pilot_env_py.yml --from-history

# Snakemake env
mamba create -c conda-forge -c bioconda -n snakemake snakemake
conda activate snakemake
## Send to file
conda env export > config/snakemake.yml

# R env
conda create -n pilot_env_r
conda activate pilot_env_r
## Install packages
conda config --add channels conda-forge
conda config --add channels defaults
conda config --add channels r
conda config --add channels bioconda
conda install r
conda install rstudio
conda install r-tidyverse
## Send to file
conda env export > config/pilot_env_r.yml

```

## Create envs on cluster
```{bash}
# PYTHON ENV
conda env create -f pilot_paper/config/pilot_env_py.yml
# doesn't work beccuse of cross-platform issues between macos and linux
#Solving environment: failed
#ResolvePackageNotFound: 

# Make afresh 
conda create -n pilot_py python=3.6 biopython
conda activate pilot_py

conda install -c anaconda opencv
conda install -c anaconda pandas
# Export to config
conda env export -n pilot_py -f pilot_paper/envs/pilot_py.yml

# DLC ENV

```


# Edit videos with Python

## Edit coordinate file

```{python}
import pandas as pd
# read in
dat = pd.read_csv('/Users/brettell/Documents/Repositories/pilot_paper/data/20201105_crop_coords.csv')
# get head
dat.head()
#
```

## Find codec of video
<https://stackoverflow.com/questions/2869281/how-to-determine-video-codec-of-a-file-with-ffmpeg>
```{bash}
ffprobe -v error -select_streams v:0 -show_entries stream=codec_name \
  -of default=noprint_wrappers=1:nokey=1 /Users/brettell/Documents/Data/20201019_pilot_dlc_training/20190613_1024_icab_hni_R.avi
```


## Crop and save videos

Tutorial: <https://docs.opencv.org/4.5.0/dd/d43/tutorial_py_video_display.html>

```{python}
# Activate environment
conda activate pilot_env_py
# Open IPython
ipython
# Import libraries
import numpy as np
import cv2 as cv
import os 

# Set path of file
path = '/Users/brettell/Documents/Data/20201019_pilot_dlc_training/20190613_1024_icab_hni_R.avi'

# Get file name without extension
file_name = os.path.split(path)[1].split('.')[0].split('_')

# Get metadata 
date = file_name[0]
time = file_name[1]
test_line = file_name[3]
tank_side = file_name[4]

# Read video from file
cap = cv.VideoCapture(path)

# Play video until completed
while cap.isOpened():
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Flip if tank side is "R"    
    if tank_side == 'R':
        frame = cv.rotate(frame, cv.ROTATE_180)
    # Show image    
    cv.imshow('frame', frame)
    # Press 'esc' to close video
    if cv.waitKey(1) == 27:
        cv.destroyAllWindows()
        cv.waitKey(1)
        break    

cap.release()
        
# Get frame width and height
wid = int(cap.get(cv.CAP_PROP_FRAME_WIDTH))
hei = int(cap.get(cv.CAP_PROP_FRAME_HEIGHT))

# Get total frame length
int(cap.get(cv.CAP_PROP_FRAME_COUNT))

# Get frames per second
int(cap.get(cv.CAP_PROP_FPS))

# Get FPS for each video in directory
data_path = '/Users/brettell/Documents/Data/20201019_pilot_dlc_training'
files = os.listdir(data_path)
for file in files:
    # get full path name
    file_full = os.path.join(data_path, file)
    # print 
    if os.path.isfile(file_full):
        cap = cv.VideoCapture(file_full)
        fps = cap.get(cv.CAP_PROP_FPS)
        print(fps)

# Do the same but on the cluster, and get total frame length    
data_path = '/nfs/ftp/private/birney-res-ftp/upload/medaka/videos/ian_pilot/all'
files = os.listdir(data_path)
files.sort() # sort files
for file in files:
    # get full path name
    file_full = os.path.join(data_path, file)
    # print 
    if os.path.isfile(file_full):
        cap = cv.VideoCapture(file_full)
        vid_len = int(cap.get(cv.CAP_PROP_FRAME_COUNT))
        print(vid_len)        
        
# Play select frames of video
start = 10000
end = 10020
for i in range(start,end):
    cap.set(cv.CAP_PROP_POS_FRAMES, i)
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Flip if tank side is "R"    
    if tank_side == 'R':
        frame = cv.rotate(frame, cv.ROTATE_180)
    # Show image    
    cv.imshow('frame', frame)
    # Press 'esc' to close video
    if cv.waitKey(1) == 27:
        cv.destroyAllWindows()
        cv.waitKey(1)
        break
cv.destroyAllWindows()
cv.waitKey(1)
           
# Show specific frames, and cycle through with spacebar
start = 10000
end = 10020
i = start
while i in range(start,end):
    cap.set(cv.CAP_PROP_POS_FRAMES, i)
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Flip if tank side is "R"    
    if tank_side == 'R':
        frame = cv.rotate(frame, cv.ROTATE_180)
    # Show image    
    cv.imshow('frame', frame)
    # Wait for spacebar to continue        
    if cv.waitKey(0) == 32:
        # Add to counter
        i += 1
    # Press 'esc' to close video
    elif cv.waitKey(0) == 27:
        cv.destroyAllWindows()
        cv.waitKey(1)
        break    
cv.destroyAllWindows()
cv.waitKey(1)

# Trackbar question:
# <https://stackoverflow.com/questions/21983062/in-python-opencv-is-there-a-way-to-quickly-scroll-through-frames-of-a-video-all>

# Pull out frame to find coordinates
write_path = '/Users/brettell/Documents/Data/20201019_pilot_dlc_training_processed'


## Whole frame
target = 10000

cap.set(cv.CAP_PROP_POS_FRAMES, target)
# Capture frame-by-frame
ret, frame = cap.read()
# if frame is read correctly ret is True
if not ret:
    print("Can't receive frame (stream end?). Exiting ...")
# Flip if tank side is "R"    
if tank_side == 'R':
    frame = cv.rotate(frame, cv.ROTATE_180)
# Get full path name
path_out = os.path.join(write_path, str(target) + '.png')
# Write frame 
cv.imwrite(path_out, frame)

## Save separate quadrants
### Take mid-points and give 10 pixels' leeway
cap.set(cv.CAP_PROP_POS_FRAMES, target)
# Capture frame-by-frame
ret, frame = cap.read()
# if frame is read correctly ret is True
if not ret:
    print("Can't receive frame (stream end?). Exiting ...")
# Flip if tank side is "R"    
if tank_side == 'R':
    frame = cv.rotate(frame, cv.ROTATE_180)
# Pull out quadrants and save
for x in ['q1', 'q2', 'q3', 'q4']:
    if x == 'q1':
        top = 0 
        bottom = round(((hei - 1) / 2) + 10) 
        left = round((wid - 1) / 2)
        right = wid - 1
    if x == 'q2':
        top = 0 
        bottom = round(((hei - 1) / 2) + 10) 
        left = 0
        right = round(((wid - 1) / 2) + 10)
    if x == 'q3':
        top = round(((hei - 1) / 2) + 5) 
        bottom = hei - 1
        left = 0
        right = round(((wid - 1) / 2) + 10)
    if x == 'q4':
        top = round(((hei - 1) / 2) + 5) 
        bottom = hei - 1
        left = round(((wid - 1) / 2) + 5)    
        right = wid  - 1  
    # Set bounding box
    cropped_img = frame[top:bottom, left:right]
    # Get full path name
    path_out = os.path.join(write_path, str(target) + '_' + x + '.png')
    # Write frame 
    cv.imwrite(path_out, cropped_img)
```

## Create new video and save

Troubleshooting help here: `https://stackoverflow.com/questions/26452909/opencv-write-frame-to-file-python`
```{python}
# Import libraries
import numpy as np
import cv2 as cv
import os

# Get key variables

in_file = '/Users/brettell/Documents/Data/20201019_pilot_dlc_training/20190613_1024_icab_hni_R.avi'
start = 2889
end = 22790
quadrant = 'q1'

# Read video from file
cap = cv.VideoCapture(in_file)

# Frame width and height
wid = int(cap.get(cv.CAP_PROP_FRAME_WIDTH))
hei = int(cap.get(cv.CAP_PROP_FRAME_HEIGHT))
# Get total frame length
vid_len = int(cap.get(cv.CAP_PROP_FRAME_COUNT))
# Get frames per second
fps = int(cap.get(cv.CAP_PROP_FPS))
# Adapt basename prefix
in_file_pref = os.path.split(in_file)[1].split('.')[0]
# Get file name without extension
meta_list = os.path.split(in_file)[1].split('.')[0].split('_')

# Get metadata 
date = meta_list[0]
time = meta_list[1]
test_line = meta_list[3]
tank_side = meta_list[4]

# Output file
out_dir = '/Users/brettell/Documents/Data/20201019_pilot_dlc_training_processed'
out_file = os.path.join(out_dir, in_file_pref + '_' + quadrant + '.mp4')

# Loop over
#for i in range(start,end):
#cap.set(cv.CAP_PROP_POS_FRAMES, i)

# Get bounding box coords for target quadrant
if quadrant == 'q1':
    top = 0 
    bottom = round(((hei - 1) / 2) + 10) 
    left = round((wid - 1) / 2)
    right = wid - 1
elif quadrant == 'q2':
    top = 0 
    bottom = round(((hei - 1) / 2) + 10) 
    left = 0
    right = round(((wid - 1) / 2) + 10)
elif quadrant == 'q3':
    top = round(((hei - 1) / 2) + 5) 
    bottom = hei - 1
    left = 0
    right = round(((wid - 1) / 2) + 10)
elif quadrant == 'q4':
    top = round(((hei - 1) / 2) + 5) 
    bottom = hei - 1
    left = round(((wid - 1) / 2) + 5)    
    right = wid  - 1
else:
    print('Invalid quadrant')

# Get size of output video
size = (right - left, bottom - top)

# Define the codec and create VideoWriter object
fourcc = cv.VideoWriter_fourcc('m', 'p', '4', 'v')
out = cv.VideoWriter(out_file, fourcc, fps, size, isColor=True)

# Capture frame-by-frame
i = start
while i in range(start,end):
    cap.set(cv.CAP_PROP_POS_FRAMES, i)
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Flip if tank side is "R"    
    if tank_side == 'R':
        frame = cv.rotate(frame, cv.ROTATE_180)
    # Crop frame
    frame = frame[top:bottom, left:right]
    # Write frame
    out.write(frame)
    # Show image    
#    cv.imshow('frame', frame)
    # Add to counter
    i += 1
    # Press 'esc' to close video
    if cv.waitKey(1) == 27:
        cv.destroyAllWindows()
        cv.waitKey(1)
        break

cap.release()
out.release()
out = None
cv.destroyAllWindows()
cv.waitKey(1)

```

## Put in script and test

```{bash}
# On local
code/scripts/20201111_split_videos.py \
  --in_file /Users/brettell/Documents/Data/20201019_pilot_dlc_training/20190613_1024_icab_hni_R.avi \
  --start 2889\
  --end 22790\
  --quadrant q1 \
  --out_dir /Users/brettell/Documents/Data/20201019_pilot_dlc_training_processed
  
# On cluster
conda activate pilot_py

pilot_paper/code/scripts/20201111_split_videos.py \
  --in_file /nfs/ftp/private/birney-res-ftp/upload/medaka/videos/ian_pilot/all/20190613_1024_icab_hni_R.avi \
  --start 2889\
  --end 22790\
  --quadrant q1 \
  --out_dir tmp
# Works!  
```

# Label frames on local

```{bash}

```

